config/routes.rb
Rails.application.routes.draw do
  root to: "artists#search"

  resources :artists, only: [:index, :show]
  get '/tracks/:id/download', to: "tracks#download", as: :download

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def search
  end

  def show
    @artist = Artist.find(params[:id])
    @tracks = MusicFinder.find_tracks(@artist)
  end

  def index
  	if params[:artist_name]
  		@artists = MusicFinder.find_artist(params[:artist_name])
   	else
   		@artists = Artist.all
   	end

    # On ne garde que les artistes qui ont des tracks
    @artists.to_a.select! { |artist| artist.track_count > 0 }
  end
end

app/controllers/tracks_controller.rb
require 'soundcloud-downloader'
require "open-uri"

class TracksController < ApplicationController
  def download
    track = Track.find(params[:id])
    downloader = SoundCloud::Downloader::Client.new(client_id: Rails.application.secrets.soundcloud_api_key)
    url = downloader.resolve(track.stream_url)

    # Makes the browser download the file
    send_data(open(url).read,
      :type => "audio/mpeg",
      :disposition => "attachment; filename=\"#{track.title}.mp3\"")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<% if @artists.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>
        </th>
        <th>Artist</th>
        <th>SoundCloud Profile </th>
        <th>Tracks count</th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>
      	<tr class="artist">
          <td>
      		  <%= image_tag artist.avatar_url, height: '50px' %>
          </td>
          <td class="tracks">
            <strong>
      		    <%= link_to artist.full_name.capitalize, artist_path(artist.id) %>
            </strong>
          </td>
      		<td class="soundcloud">
      			<%= link_to '&#9729;'.html_safe, artist.permalink_url %>
          </td>
          <td class="count">
      			<%= artist.track_count %>
      		</td>
      	</tr>
      <% end %>
    </tbody>
  </table>  
<% else %>
  <div class="alert alert-danger" role="alert">No artist found.</div>
<% end %>

app/views/artists/search.html.erb
<%= form_tag artists_path, method: :get do %>
	<%= text_field_tag :artist_name, nil, placeholder: "Cherchez un artiste" %>
	<%= submit_tag "Recherchez !" %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.full_name %>'s tracks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>
      </th>
      <th>Name</th>
      <th>Duration</th>
      <th>Download</th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td>
          <%= image_tag track.artwork_url, height: '30px' %>
        </td>
        <td>
          <%= track.title %>
        </td>
        <td>
          <%= (Time.mktime(0) + track.duration / 1000).strftime("%H:%M:%S") %>
        </td>
        <td>
          <%= link_to "Download", download_path(track.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
<!-- https://github.com/gabriel-dehan/soundcloud-downloader -->

<!-- DEVISE -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundownload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/flashes" %>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-bootstrap-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	      <li>
	        <%= link_to t(".sign_up", default: "Sign up"), root_path %>
	      </li>
	      <li>
	        <%= link_to t(".sign_in", default: "Sign in"), root_path %>
	      </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>